# Generated by Django 5.1 on 2026-03-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(blank=True, default='#6c757d', max_length=7)),
                ('icone', models.CharField(blank=True, default='bi-tag', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], db_index=True, max_length=10)),
                ('data', models.DateField(db_index=True)),
                ('recorrente', models.BooleanField(default=False)),
                ('frequencia', models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10, null=True)),
                ('dias_semana', models.CharField(blank=True, max_length=20, null=True)),
                ('dia_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financas.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'data', 'tipo'], name='financas_mo_usuario_8724a8_idx')],
            },
        ),
    ]
